добавил hw4
eugene-okulik/Aleksey pull request #3
Opened 2024-10-13 20:10 UTC by zhuzepa

2024-10-14 11:58 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошел ))

2024-10-14 11:58 UTC, eugene-okulik commented on homework/aleksey_prince/Homework_4/hw4.py
> +my_dict['dict']['i am a tuple'] = 'WTF tuple??'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-10-14 12:57 UTC, zhuzepa commented on homework/aleksey_prince/Homework_4/hw4.py
> +my_dict['dict']['i am a tuple'] = 'WTF tuple??'
Жесть конечно)
Вроде добавил)

2024-10-15 08:35 UTC, eugene-okulik approved these changes

2024-10-15 08:35 UTC, merged