добавил ДЗ 5
eugene-okulik/Aleksey pull request #4
Opened 2024-10-17 17:16 UTC by zhuzepa

Честно сказать второе задание сложное было, пришлось подглядеть, я пытался понять логику и не понял особо, до этого не работал index + срез wtf)

2024-10-18 08:36 UTC, eugene-okulik requested changes

2024-10-18 08:36 UTC, eugene-okulik commented on homework/aleksey_prince/Homework_5/hw5.py
> +country = person[4]
Обращение к элементам списка по индексу - это крайняя мера, к которой нужно прибегать, если других вариантов нет. Здесь бы отлично подошла распаковка.

2024-10-18 08:36 UTC, eugene-okulik commented on homework/aleksey_prince/Homework_5/hw5.py
> +print(f'Students {students[0]}, {students[1]}, {students[2]} study these subjects: {subjects_2}')
с subjects хорошо, а с students - не очень, так как это обращение по индексам, которое отлично заменяется с помощью join, но это решение тебе почему-то не понравилось и ты его закоментировал.

2024-10-18 13:43 UTC, zhuzepa commented
Вроде исправил всё

2024-10-18 13:44 UTC, zhuzepa commented on homework/aleksey_prince/Homework_5/hw5.py
> +country = person[4]
Прослушал видать на видео :(
Путал индекс и распаковку

2024-10-18 13:48 UTC, zhuzepa commented on homework/aleksey_prince/Homework_5/hw5.py
> +print(f'Students {students[0]}, {students[1]}, {students[2]} study these subjects: {subjects_2}')
Я не знал, что join разделяет между слов + запятая если я её укажу, я думал что она будет и после Sidorov и как ее убрать.

А получается, что последнее слово не включается как я понял.

2024-10-19 08:40 UTC, eugene-okulik commented on homework/aleksey_prince/Homework_5/hw5.py
> +print(f'Students {students[0]}, {students[1]}, {students[2]} study these subjects: {subjects_2}')
Ага, если добавлять запятую не с помощью join, то запаришься там. А join - вообще красавчик.

2024-10-19 08:41 UTC, eugene-okulik approved these changes

2024-10-19 08:41 UTC, merged